---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 810f1e91a4aaa47c807cbb173db189b6c6857a79
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=zeppelins-gateway&var-version=1.0-SNAPSHOT
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/zeppelins-common-framework/zeppelins-gateway
  labels:
    app: zeppelins-gateway
    provider: fabric8
    version: 0.1
    group: com.hybris.openplatform
  name: zeppelins-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zeppelins-gateway
      provider: fabric8
      group: com.hybris.openplatform
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 810f1e91a4aaa47c807cbb173db189b6c6857a79
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gateway&var-version=1.0-SNAPSHOT
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/common-framework/gateway
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        app: zeppelins-gateway
        provider: fabric8
        version: 0.1
        group: com.hybris.openplatform
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ${docker.image.prefix}/${project.artifactId}:latest
        imagePullPolicy: Always
        name: zeppelins-gateway
        ports:
        - containerPort: 8085
          protocol: TCP
        securityContext:
          privileged: false
        imagePullSecrets:
          - name: mysecrets
