---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 810f1e91a4aaa47c807cbb173db189b6c6857a79
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/zeppelins-common-framework/zeppelins-gateway
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
  labels:
    app: zeppelins-gateway
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: com.hybris.openplatform
  name: zeppelins-gateway-service
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: zeppelins-gateway
    provider: fabric8
    group: com.hybris.openplatform
  type: LoadBalancer
