---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    maven.fabric8.io/dockerServerId: ${docker.image.prefix}
  labels:
    app: zeppelins-gateway
    provider: fabric8
    version: "0.1"
    group: com.hybris.openplatform
  name: mysecrets
  namespace: default
type: kubernetes.io/dockercfg

